package com.twistlet.kiptanui.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
)
public class Role  implements java.io.Serializable {


     private String roleName;
     private String label;
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);

    public Role() {
    }

	
    public Role(String roleName) {
        this.roleName = roleName;
    }
    public Role(String roleName, String label, Set<UserRole> userRoles) {
       this.roleName = roleName;
       this.label = label;
       this.userRoles = userRoles;
    }
   
     @Id 

    
    @Column(name="role_name", unique=true, nullable=false, length=50)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    
    @Column(name="label", length=50)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }




}


