package com.twistlet.kiptanui.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
)
public class User  implements java.io.Serializable {


     private String id;
     private String password;
     private String name;
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);

    public User() {
    }

	
    public User(String id, String password, String name) {
        this.id = id;
        this.password = password;
        this.name = name;
    }
    public User(String id, String password, String name, Set<UserRole> userRoles) {
       this.id = id;
       this.password = password;
       this.name = name;
       this.userRoles = userRoles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=150)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="password", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }




}


